<?php

namespace ContainerQQdVxfR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9Jx8J1EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9Jx8J1E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9Jx8J1E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'signalisation' => ['privates', '.errored..service_locator.9Jx8J1E.App\\Entity\\Signalisation', NULL, 'Cannot autowire service ".service_locator.9Jx8J1E": it references class "App\\Entity\\Signalisation" but no such service exists.'],
        ], [
            'signalisation' => 'App\\Entity\\Signalisation',
        ]);
    }
}
