<?php

namespace ContainerQQdVxfR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QBfrxK7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qBfrxK7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qBfrxK7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorie' => ['privates', '.errored..service_locator.qBfrxK7.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.qBfrxK7": it references class "App\\Entity\\Categorie" but no such service exists.'],
            'evenementRepo' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
        ], [
            'categorie' => 'App\\Entity\\Categorie',
            'evenementRepo' => 'App\\Repository\\EvenementRepository',
        ]);
    }
}
