<?php

namespace ContainerQQdVxfR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TYrO2vSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TYrO2vS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TYrO2vS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'feedback' => ['privates', '.errored..service_locator.TYrO2vS.App\\Entity\\Feedback', NULL, 'Cannot autowire service ".service_locator.TYrO2vS": it references class "App\\Entity\\Feedback" but no such service exists.'],
        ], [
            'feedback' => 'App\\Entity\\Feedback',
        ]);
    }
}
