<?php

namespace ContainerQQdVxfR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Z8xh0Z9.App\Entity\Categorie' shared service.
     *
     * @return \App\Entity\Categorie
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Z8xh0Z9": it references class "App\\Entity\\Categorie" but no such service exists.');
    }
}
