<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IZBq7FgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iZBq7Fg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iZBq7Fg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeEvent' => ['privates', '.errored..service_locator.iZBq7Fg.App\\Entity\\TypeEvent', NULL, 'Cannot autowire service ".service_locator.iZBq7Fg": it references class "App\\Entity\\TypeEvent" but no such service exists.'],
        ], [
            'typeEvent' => 'App\\Entity\\TypeEvent',
        ]);
    }
}
