<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y5E4M3QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y5E4M3Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y5E4M3Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ratingEvent' => ['privates', '.errored..service_locator.Y5E4M3Q.App\\Entity\\RatingEvent', NULL, 'Cannot autowire service ".service_locator.Y5E4M3Q": it references class "App\\Entity\\RatingEvent" but no such service exists.'],
        ], [
            'ratingEvent' => 'App\\Entity\\RatingEvent',
        ]);
    }
}
