<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mbnxc2pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mbnxc2p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mbnxc2p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'label' => ['privates', '.errored..service_locator.mbnxc2p.App\\Entity\\Label', NULL, 'Cannot autowire service ".service_locator.mbnxc2p": it references class "App\\Entity\\Label" but no such service exists.'],
        ], [
            'label' => 'App\\Entity\\Label',
        ]);
    }
}
