<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LuUc2_JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LuUc2.J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LuUc2.J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentEvent' => ['privates', '.errored..service_locator.LuUc2.J.App\\Entity\\CommentEvent', NULL, 'Cannot autowire service ".service_locator.LuUc2.J": it references class "App\\Entity\\CommentEvent" but no such service exists.'],
        ], [
            'commentEvent' => 'App\\Entity\\CommentEvent',
        ]);
    }
}
