<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dr4c9LfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dr4c9Lf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dr4c9Lf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comment' => ['privates', '.errored..service_locator.dr4c9Lf.App\\Entity\\Comments', NULL, 'Cannot autowire service ".service_locator.dr4c9Lf": it references class "App\\Entity\\Comments" but no such service exists.'],
        ], [
            'comment' => 'App\\Entity\\Comments',
        ]);
    }
}
