<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C7oxAYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c7ox_aY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c7ox_aY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'participant' => ['privates', '.errored..service_locator.c7ox_aY.App\\Entity\\Participant', NULL, 'Cannot autowire service ".service_locator.c7ox_aY": it references class "App\\Entity\\Participant" but no such service exists.'],
        ], [
            'participant' => 'App\\Entity\\Participant',
        ]);
    }
}
