<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidatureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EMIKjH9.App\Entity\Candidature' shared service.
     *
     * @return \App\Entity\Candidature
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.EMIKjH9": it references class "App\\Entity\\Candidature" but no such service exists.');
    }
}
