<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LuUc2.J.App\Entity\CommentEvent' shared service.
     *
     * @return \App\Entity\CommentEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.LuUc2.J": it references class "App\\Entity\\CommentEvent" but no such service exists.');
    }
}
