<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedbackService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TYrO2vS.App\Entity\Feedback' shared service.
     *
     * @return \App\Entity\Feedback
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TYrO2vS": it references class "App\\Entity\\Feedback" but no such service exists.');
    }
}
