<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInteractionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0UuiEPa.App\Entity\Interactions' shared service.
     *
     * @return \App\Entity\Interactions
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0UuiEPa": it references class "App\\Entity\\Interactions" but no such service exists.');
    }
}
