<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLabelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mbnxc2p.App\Entity\Label' shared service.
     *
     * @return \App\Entity\Label
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.mbnxc2p": it references class "App\\Entity\\Label" but no such service exists.');
    }
}
