<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Yha0JhJ.App\Entity\Postes' shared service.
     *
     * @return \App\Entity\Postes
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Yha0JhJ": it references class "App\\Entity\\Postes" but no such service exists.');
    }
}
