<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.c7ox_aY.App\Entity\Participant' shared service.
     *
     * @return \App\Entity\Participant
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.c7ox_aY": it references class "App\\Entity\\Participant" but no such service exists.');
    }
}
