<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartenaireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jJ_XUWw.App\Entity\Partenaire' shared service.
     *
     * @return \App\Entity\Partenaire
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.jJ_XUWw": it references class "App\\Entity\\Partenaire" but no such service exists.');
    }
}
