<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRatingEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Y5E4M3Q.App\Entity\RatingEvent' shared service.
     *
     * @return \App\Entity\RatingEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Y5E4M3Q": it references class "App\\Entity\\RatingEvent" but no such service exists.');
    }
}
