<?php

namespace Container0xYFKXN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignalisationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9Jx8J1E.App\Entity\Signalisation' shared service.
     *
     * @return \App\Entity\Signalisation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.9Jx8J1E": it references class "App\\Entity\\Signalisation" but no such service exists.');
    }
}
