<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xYFKXN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xYFKXN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0xYFKXN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0xYFKXN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0xYFKXN\App_KernelDevDebugContainer([
    'container.build_hash' => '0xYFKXN',
    'container.build_id' => '891013e2',
    'container.build_time' => 1619005572,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0xYFKXN');
